### PR TITLE
Support using an external video buffer on PB12

### PR DESCRIPTION
**Pull request by penfold42**
- compile time option
- active low
- when enabled, SPI data out is always driven

### CODE REVIEW

**Comment by keirf** [comment]
Hi, this is merged into keirf:pins. It is only build tested! Can you take a look, see what you think, and try it out?

Note I moved DISPEN to PA15. The reason is fairly weak: It seems good to keep the wider expanse of 5v-tolerant pins on GPIOB available for hot-key usage. If we can keep all hot-key control on the one pin bank, it is potentially less confusing for future user configuration. Like I say, it's not a mega strong reason -- if you had a particular reason for PB12 perhaps it will move back.

**Comment by keirf** [comment]
By the way, if you get startup hangs or issues on keirf:pins, let's dig into it. You may well have a different and more "production" setup than me, eg my Gotek and FF-OSD are always started in strict sequence from Bootloader Mode, so the power on timing is nothing at all like a real user's experience.

**Comment by keirf** [comment]
I had forgotten to push the patch to Github. Now done so you should be able to see it.

**Comment by penfold42** [comment]
All good with PA15

tested today and it looks good so far

**Comment by keirf** [comment]
This is merged to master.

**Pull request closed without merging**
